name: 电视直播源更新

on:
  schedule:
    - cron: '0 22 1 * *'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: GetTime
        id: date
        run: echo "::set-output name=date::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"

      - name: Run iptv
        run: python ${{ github.workspace }}/live.py

      - name: 更新 EPG.xml 和 README.md
        run:  |      
          rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
          echo "good_channels.m3u 的网址 已于 ${{ steps.date.outputs.date }} 更新，本仓库访客数：![Visitor's Count](https://profile-counter.glitch.me/pxiptv_TV/count.svg)" > README.md
        
      - name: 提交更改
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if [[ -f "good_channels.m3u" ]]; then
            git add good_channels.m3u
            git commit -m "Automatic update"
            git push
          else
            echo "good_channels.m3u does not exist, skipping commit."
          fi

          if [[ -f "EPG.xml" ]]; then
            git add EPG.xml
          fi
          git add README.md
          git commit -m "${{ steps.date.outputs.date }}"
          git push

          if [[ -f "good_channels.m3u" ]]; then
            current_datetime=$(date +"%Y%m%d_%H%M%S")
            mkdir -p history
            cp good_channels.m3u history/"${current_datetime}_good_channels.m3u"
            git add history/"${current_datetime}_good_channels.m3u"
            git commit -m "Archive file with timestamp"
            git push
          else
            echo "good_channels.m3u does not exist, skipping archive."
          fi

env:
  TZ: Asia/Shanghai
